version: '3.7'
services:
  prisma:
    container_name: prisma
    ports:
      - '5555:5555'
    build:
      context: backend/prisma
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - /app/prisma
      - /app/generated
  backend:
    container_name: backend
    ports:
      - '4000:4000'
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
      - /app/prisma
      - /app/generated
  frontend:
    container_name: frontend
    ports:
      - '3000:3000'
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/components:/app/components
      - ./frontend/interfaces:/app/interfaces
      - ./frontend/pages:/app/pages
      - ./frontend/utils:/app/utils
      - ./frontend/graphql:/app/graphql
      - /app/node_modules
      - /app/.next
