version: '3.7'
services:
  prisma:
    container_name: prisma
    ports:
      - '5555:5555'
    build:
      context: backend
      dockerfile: Dockerfile.prisma
    command: 'prisma2 dev'
    volumes:
      - ./backend/src:/app/src
      - node_modules:/app/node_modules
      - prisma:/app/prisma
      - generated:/app/generated
  backend:
    container_name: backend
    depends_on:
      - prisma
    ports:
      - '4000:4000'
    build:
      context: backend
      dockerfile: Dockerfile.backend
    command: 'npm start'
    volumes:
      - ./backend/src:/app/src
      - node_modules:/app/node_modules
      - prisma:/app/prisma
      - generated:/app/generated
volumes:
  node_modules:
  prisma:
  generated:
