FROM node:10.16.0
RUN npm install -g --unsafe-perm prisma2

RUN mkdir /app
WORKDIR /app

COPY package*.json tsconfig.json ./
COPY prisma ./prisma/
RUN ls -la 
# RUN ls -la /app/prisma/migrations
# RUN npm install
# RUN prisma2 lift save
# RUN ls -la /app/prisma
# RUN prisma2 lift up \\
#     && ls -la node_modules


# RUN npm install \\
#     && prisma2 lift save -n migrate \\
#     && prisma2 lift up \\ 
#     && prisma2 dev

RUN npm install
#RUN prisma2 lift save -n migrate 
#RUN prisma2 lift up
# RUN prisma2 dev

#CMD [ "npm", "start"]
